function [hLine] = initLine(xData,yData, lineType, hFig, graphPos, bkColor, graphColor,xLim, yLim)
    hAxes = axes( ...
                  'Parent',hFig, ...
                  'OuterPosition',graphPos ...
                 );
    switch lineType
        case 0
            hLine = plot(hAxes,xData,yData,graphColor);
        case 1
            hLine = stem(hAxes,xData,yData,graphColor);
        otherwise
            hLine = plot(hAxes,xData,yData,graphColor);
    end
    set(hAxes, ...
               'Color', bkColor, ...
               ...%'XColor',[0 0 0.4], ...
                ...%'YColor',[0 0 0.4], ...
                'XLim', xLim, ...
                'YLim', yLim ...
        );
    grid(hAxes);
end