function [hFig] = initFig(name,bgColor,colorMap)
    hFig = figure( ...
                   'Name',name, ...
                   'NumberTitle','off', ...
                   ...%'Toolbar','none', ...
                   ...%'Menubar','none', ...
                   ...%'Renderer','opengl',...
                   'Color',bgColor, ...
                   'Colormap',colorMap ...
                 );
end